language: ruby
sudo: false
dist: trusty
cache: bundler
addons:
  apt:
    packages:
    - bind9

matrix:
  include:
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: ruby-head
    - rvm: jruby-head
      env:
        - JRUBY_OPTS="--debug -X+O"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
